
# # Stage 1: Building Angular Application
# FROM node:18-slim AS build

# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build --prod

# # Stage 2: Serving with NGINX
# FROM nginx:stable-alpine
# COPY --from=build /usr/src/app/dist/client /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

# #note: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d